### PR TITLE
Fix parse MPM and Optimization of type

### PR DESCRIPTION
**Pull request by mitu217**
I will fixing the following

- id of payload should be int
- substring should return err (#10)
- RFUForEMVCo should be array values
- UnreservedTemplates should be array values

### CODE REVIEW

**Comment by dongri** [comment]
帰ってきたぞ！ｗ

**Comment by dongri** [comment]
1. emv_parser.go
emv_mpm_parser.goのいいかもしらないですね

2. ID関して
Screen Shot 2019-06-18 at 18 07 09
別に実装上はintでも全然問題ないですが、ドキュメント通りにstringにしたいです

3. MerchantAccountInformation -> MerchantAccountInformationTemplates
Screen Shot 2019-06-18 at 18 05 52
特別な理由なしドキュメント通りの名前にしたいです

その他素晴らしいです
[LGTM](https://lgtm.lol/i/471)

**Comment by mitu217** [comment]
I fixed pointed issue.

In addition, file division and tests were added.

**Comment by mitu217** [comment]
Only mpm packages, coverage will be 97.9%

**Comment by mitu217** [comment]
Remove the `wip` after adding the validation.

**Comment by mitu217** [comment]
added validate!

generatePayload have been had issue, so fixed it

Please, review 🙇

**Comment by dongri** [comment]
[LGTM](https://lgtm.lol/i/432)

**Pull request merged**
